## DOCKER COMPOSE VERSION
version: "3.7"

## DEFINE SERVICES
services:

  ## DEMO
  demo:
    build:
      context: ./App
      target: Development
    image: pkeech/winrm-demo:dev
    container_name: WINRM_DEMO
    volumes:
      - ./App:/app