## DOCKER COMPOSE VERSION
version: "3.7"

## DEFINE SERVICES
services:
  ## NGINX (WEB SERVER) - THIS DISABLES NGINX
  nginx:
    image: alpine:latest
    command: "true"
    entrypoint: "true"

  ## DEMO
  demo:
    build:
      context: ./App
      target: Development
    image: pkeech/winrm-demo:dev
    container_name: WINRM_DEMO
    ports:
      - 8080:8080
    volumes:
      - ./App:/app