## Define GitHub Action Workflow Name
name: Deployment

## When Pull Request to Master is Created
on:
  pull_request:
    branches: 
      - master
  workflow_dispatch:

## Define Workflow
jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      ## STEP 0: Checkout Source
      - uses: actions/checkout@v2
      
      ## STEP 1: Perform Code Coverage (CodeCov)
      - name: CodeCov
        uses: codecov/codecov-action@v1.0.13
        with:          
          token: ${{ secrets.CODECOV_TOKEN }}
      
      ## STEP 2: Test Image Depenedencies (Trivy)
      - name: Trivy
        
             
      ## STEP 3: SLACK Notification
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'A new version of Docker-WinRM-Demo (${{ steps.new_version.outputs.next-version }}) was release and published to Docker Hub' 
